[project]
name = "shot-tabular"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.0.0",
    "pandas>=2.3.3",
    "pyarrow>=23.0.1",
    "pydantic>=2.12.5",
    "sal-xarray>=0.2.2",
    "uda-xarray>=0.2.3",
]
[project.scripts]
st = "shot_tabular.main:main"

[tool.setuptools]
packages = ["shot_tabular"]

[dependency-groups]
dev = [
    "pylint>=4.0.5",
    "ruff>=0.15.12",
    "ty>=0.0.32",
]
